# Generated by Django 6.0.5 on 2026-06-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
